function getDeck() {
  return { black: black(), white: white() };
}

function black() {
  return [
    "A romantic candlelit dinner would be incomplete without __________.",
    "In a past life, I was __________",
    "I was reborn the way I am because in a past life, I was __________",
    "I almost reached nirvana once, but didn't because of __________",
    "What happens after you die?",
    "The fastest way to attain enlightenment is __________.",
    "Alternative medicine is now embracing the curative powers of __________.",
    "Ah yes, my favorite tantric sex position, __________",
    "Your alternate identity in San Junipero.",
    "And I would have gotten away with it, too, if it hadn't been for __________.",
    "During sex, I like to think about __________.",
    "He who controls __________ controls the world.",
    "How am I maintaining my relationship status?",
    "I do not know with what weapons World War III will be fought, but World War IV will be fought with __________.",
    "I drink to forget __________.",
    "I got 99 problems but __________ ain't one.",
    "I learned the hard way that you can't cheer up a grieving friend with __________.",
    "I wish I hadn't lost the instruction manual for __________.",
    "I'm sorry, Professor, but I couldn't complete my homework because of __________.",
    "In 1,000 years, when paper money is but a distant memory, __________ will be our currency.",
    "In L.A. County Jail, word is you can trade 200 cigarettes for __________.",
    "In Michael Jackson's final moments, he thought about __________.",
    "In the distant future, historians will agree that __________ marked the beginning of America's decline.",
    "It's a pity that kids these days are all getting involved with __________.",
    "It's a trap!",
    "Life was difficult for cavemen before __________.",
    "Maybe she's born with it. Maybe it's __________.",
    "Next from J.K. Rowling: Harry Potter and the Chamber of __________.",
    "Science will never explain the origin of __________.",
    "TSA guidelines now prohibit __________ on airplanes.",
    "This is the way the world ends / This is the way the world ends / Not with a bang but with __________.",
    "War! What is it good for?",
    "What am I giving up for Lent?",
    "What are my parents hiding from me?",
    "What ended my last relationship?",
    "What gets better with age?",
    "What never fails to liven up the party?",
    "What will always get you laid?",
    "What would grandma find disturbing, yet oddly charming?",
    "What's Teach for America using to inspire inner city students to succeed?",
    "What's a girl's best friend?",
    "What's the gift that keeps on giving?",
    "What's the next Happy Meal toy?",
    "What's there a ton of in heaven?",
    "When I am President of the United States, I will create the Department of __________.",
    "Why can't I sleep at night?",
    "Why do I hurt all over?",
    "__________. That's how I want to die.",
    "__________? There's an app for that.",
  ];
}

function white() {
  return [
   "72 virgins",
   "A hot mess",
   "The Dalai Lama",
   "Barack Obama",
   "The Columbia Core Curriculum",
   "The Bechdel test",
   "Komodo, the dragon warrior",
   "Crazy, karmic tantric sex",
   "Action seal",
   "Orchestrated objective reduction",
   "Deathism",
   "Getting stuck inside John Searle's Chinese room",
   "The Tibetan Game of Liberation",
   "Karma Police",
   "Orgasmic breathing",
   "An episode of Black Mirror",
   "Esoteric Tibetan Buddhism",
   "The fear of death",
   "The Four Noble Truths",
   "The illusion of free will",
   "MEMES",
   "Nirvana, not like the band, but you know what I mean",
   "Feelings of cosmic insignificance",
   "Spoooooky action at a distance",
   "Tulku time",
   "A near-death experience",
   "Kabbalah",
   "The Singularity",
   "Enlightenment itself",
   "Living in a computer simulation",
   "The Matrix",
   "The implicate order",
   "The Tao of Physics",
   "Seeing the bright lights",
   "I suffer, therefore I am",
   "The Copenhagen interpretation of the quantum universe",
   "The conventional self",
   "A dharma bum",
   "The pedagogy of the oppressed",
   "An ayahuasca shaman",
   "Tripping on DMT",
   "Space-time and beyond",
   "64 Tantric Acts of Gay Male Love",
   "Six Yogas of Naropa",
   "A glitch in the system",
   "A Hitchbot's Guide to the Galaxy",
   "Becoming one with the brahman of the universe",
   "Tech imperialism",
   "Elon Musk's greatest nightmare",
   "Binging Westworld on Netflix",
   "Comparing apples and oranges",
   "Roko's basilisk",
   "Deepak Chopra",
   "A spiritual cleansing of Butler library",
   "BEES ARE DYING AT AN ALARMING RATE",
   "Free Insomnia Cookies",
   "Vipassana meditation",
   "Wake the echoes of the Hudson Valley",
   "A Ponzi scheme run by Deepak Chopra's book publisher",
   "Fake news",
   "Putting the ass in astral projection",
   "A hot mess",
   "Being a motherfucking sorcerer",
   "Dying of dysentery",
   "Eating all of the cookies before the AIDS bake-sale",
   "Ripping into a man's chest and pulling out his still-beating heart",
   "The Big Bang",
   "The Holy Bible",
   "The Pope",
   "The Rapture",
   "The folly of man",
   "The forbidden fruit",
   "The four arms of Vishnu",
   "The gay liberal agenda",
   "The inevitable heat death of the universe",
   "Tripping balls",
  ];
}

exports.getDeck = getDeck;
